#!/usr/bin/env python3
"""nginx vhost 設定を stacks/*/docker-compose.yml のラベルから生成する。

`docker compose config --format json` で core/compose.yaml + 全 stacks を合成し、
`site.host` / `site.upstream` / `site.port` ラベルを持つサービスごとに
nginx/template/site.conf.template から vhost ファイルを生成する。

Docker デーモンにも socket にも触らない（compose ファイルを読むだけ）。
生成は人間 or scripts/up.sh が明示的に実行したときだけ走る。

安全装置: stacks で言及されておらず `default` ネットワークに落ちたままの
サービスが 1 つでもあれば、アプリ側の構成変更に気づけていない可能性が高いため
エラーで停止し、conf は一切書き換えない。
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONF_D = ROOT / "core" / "nginx" / "conf.d"
TEMPLATE = ROOT / "core" / "nginx" / "template" / "site.conf.template"

# core/compose.yaml が持つサービス。専用ネットワークの割り当て対象外で、
# default ネットワークに残っていてもオーファン検査の対象にしない。
CORE_SERVICES = {"nginx", "dnsmasq"}

GENERATED_MARKER = "# --- generated by scripts/gen-nginx-conf.py. DO NOT EDIT BY HAND. ---\n"


def render_compose() -> Path:
    out = subprocess.run(
        ["bash", str(ROOT / "scripts" / "render-compose.sh")],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    return Path(out)


def load_config(compose_file: Path) -> dict:
    result = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "config", "--format", "json"],
        check=True, capture_output=True, text=True,
    )
    return json.loads(result.stdout)


def main() -> int:
    compose_file = render_compose()
    cfg = load_config(compose_file)
    services = cfg.get("services", {})

    orphans = sorted(
        name for name, svc in services.items()
        if name not in CORE_SERVICES and "default" in (svc.get("networks") or {})
    )
    if orphans:
        print(
            "エラー: 専用ネットワークに載っていないサービスがあります: "
            f"{orphans}\n"
            "アプリ側が構成を変更した(サービスを追加した)可能性があります。"
            "stacks/*/docker-compose.yml に追記してから再実行してください。"
            " conf は変更していません。",
            file=sys.stderr,
        )
        return 1

    sites = {}
    for name, svc in services.items():
        labels = svc.get("labels") or {}
        if "site.host" not in labels:
            continue
        host = labels["site.host"]
        upstream = labels.get("site.upstream", name)
        port = labels.get("site.port")
        if not port:
            print(f"エラー: サービス {name} に site.host はあるが site.port がありません", file=sys.stderr)
            return 1
        sites[host] = (upstream, port, name)

    template = TEMPLATE.read_text()

    # 前回生成した vhost のうち、今回対象にならなかったものを削除する
    # (アプリを stacks から削除したときに古い conf が残り続けるのを防ぐ)
    for existing in CONF_D.glob("*.conf"):
        if existing.name in ("default.conf", "00-http.conf"):
            continue
        text = existing.read_text()
        if text.startswith(GENERATED_MARKER) and existing.stem not in sites:
            existing.unlink()
            print(f"削除: {existing} (対応する site.host が無くなりました)")

    for host, (upstream, port, service_name) in sorted(sites.items()):
        out_path = CONF_D / f"{host}.conf"
        content = GENERATED_MARKER + template.replace("__HOST__", host) \
            .replace("__UPSTREAM__", upstream) \
            .replace("__PORT__", str(port))
        out_path.write_text(content)
        print(f"生成: {out_path} (host={host}, upstream={upstream}:{port}, service={service_name})")

    if not sites:
        print("対象となる site.host ラベル付きサービスはありませんでした")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
