#!/usr/bin/env python3
"""nginx vhost 設定を stacks/*/docker-compose.yml のラベルから生成する。

`docker compose config --format json` で core/compose.yaml + 全 stacks を合成し、
`site.host` / `site.upstream` / `site.port` ラベルを持つサービスごとに
nginx/template/site.conf.template から vhost ファイルを生成する。

Docker デーモンにも socket にも触らない（compose ファイルを読むだけ）。
生成は人間 or scripts/up.sh が明示的に実行したときだけ走る。

安全装置: 専用ネットワーク(`net-<app名>`)に載っていないサービスが1つでもあれば、
アプリ側の構成変更(サービス追加、独自 networks の宣言等)に気づけていない可能性が
高いためエラーで停止し、conf は一切書き換えない。`default` ネットワークだけでなく、
アプリ側 compose が独自に宣言した networks(例: `webnet`)に取り残されたケースも
対象にする(`!override` を書き忘れたサービスがある場合など)。
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONF_D = ROOT / "core" / "nginx" / "conf.d"
TEMPLATE = ROOT / "core" / "nginx" / "template" / "site.conf.template"

# core/compose.yaml が持つサービス。専用ネットワークの割り当て対象外で、
# default ネットワークに残っていてもオーファン検査の対象にしない。
CORE_SERVICES = {"nginx", "dnsmasq"}

GENERATED_MARKER = "# --- generated by scripts/gen-nginx-conf.py. DO NOT EDIT BY HAND. ---\n"


def _run(cmd: list[str]) -> str:
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"エラー: コマンドが失敗しました: {' '.join(cmd)}", file=sys.stderr)
        print(e.stderr, file=sys.stderr, end="")
        raise SystemExit(1)
    return result.stdout


def render_compose() -> Path:
    return Path(_run(["bash", str(ROOT / "scripts" / "render-compose.sh")]).strip())


def load_config(compose_file: Path) -> dict:
    out = _run(["docker", "compose", "-f", str(compose_file), "config", "--format", "json"])
    return json.loads(out)


def main() -> int:
    compose_file = render_compose()
    cfg = load_config(compose_file)
    services = cfg.get("services", {})

    # net-<app名> は new-app.sh の雛形が常に付与する専用ネットワーク名の規約。
    # これ以外のネットワーク(暗黙の default だけでなく、アプリ側 compose が
    # 独自に宣言した webnet 等も含む)に載っているサービスは、!override し忘れた
    # か、stacks/*/docker-compose.yml に追記し忘れたサービスの可能性が高い。
    orphans = sorted(
        name for name, svc in services.items()
        if name not in CORE_SERVICES
        and any(not net.startswith("net-") for net in (svc.get("networks") or {}))
    )
    if orphans:
        print(
            "エラー: 専用ネットワーク(net-<app名>)に載っていないサービスがあります: "
            f"{orphans}\n"
            "アプリ側が構成を変更した(サービスを追加した/独自networksを宣言した)"
            "可能性があります。stacks/*/docker-compose.yml で !override してから"
            "再実行してください。conf は変更していません。",
            file=sys.stderr,
        )
        return 1

    sites = {}
    for name, svc in services.items():
        labels = svc.get("labels") or {}
        if "site.host" not in labels:
            continue
        host = labels["site.host"]
        upstream = labels.get("site.upstream", name)
        port = labels.get("site.port")
        if not port:
            print(f"エラー: サービス {name} に site.host はあるが site.port がありません", file=sys.stderr)
            return 1
        if host in sites:
            print(
                f"エラー: site.host '{host}' がサービス {sites[host][2]} と {name} の"
                "両方で使われています。conf は変更していません。",
                file=sys.stderr,
            )
            return 1
        sites[host] = (upstream, port, name)

    template = TEMPLATE.read_text()

    # 前回生成した vhost のうち、今回対象にならなかったものを削除する
    # (アプリを stacks から削除したときに古い conf が残り続けるのを防ぐ)
    for existing in CONF_D.glob("*.conf"):
        if existing.name in ("default.conf", "00-http.conf"):
            continue
        text = existing.read_text()
        if text.startswith(GENERATED_MARKER) and existing.stem not in sites:
            existing.unlink()
            print(f"削除: {existing} (対応する site.host が無くなりました)")

    for host, (upstream, port, service_name) in sorted(sites.items()):
        out_path = CONF_D / f"{host}.conf"
        content = GENERATED_MARKER + template.replace("__HOST__", host) \
            .replace("__UPSTREAM__", upstream) \
            .replace("__PORT__", str(port))
        out_path.write_text(content)
        print(f"生成: {out_path} (host={host}, upstream={upstream}:{port}, service={service_name})")

    if not sites:
        print("対象となる site.host ラベル付きサービスはありませんでした")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
